services:
  hmiaf-db:
    image: mariadb/latest
    build: hmiaf-db
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=testuser"
      - "MYSQL_PASSWORD=admin123"
    